# Generated by Django 3.0.6 on 2020-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunarEclipse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(max_length=30)),
                ('eclipse_info', models.TextField()),
                ('eclipse_image_route', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SolarEclipse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(max_length=30)),
                ('eclipse_info', models.TextField()),
                ('eclipse_image_route', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
    ]
