# Generated by Django 3.0.6 on 2020-06-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astronomerweb', '0002_auto_20200601_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LunarEclipse',
            new_name='Eclipse',
        ),
        migrations.DeleteModel(
            name='SolarEclipse',
        ),
    ]
