# Generated by Django 3.0.7 on 2020-07-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomerweb', '0005_auto_20200711_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='eclipses',
            name='eclipse_datetime',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='eclipses',
            name='eclipse_time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
