# Generated by Django 3.0.7 on 2020-07-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomerweb', '0006_auto_20200711_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eclipses',
            name='eclipse_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eclipses',
            name='eclipse_datetime',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='eclipses',
            name='eclipse_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='eclipses',
            name='eclipse_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eclipses',
            name='eclipse_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eclipses',
            name='solar_lunar',
            field=models.CharField(max_length=50),
        ),
    ]
