# Generated by Django 3.0.7 on 2020-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomerweb', '0007_auto_20200711_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='eclipses',
            name='eclipse_image_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eclipses',
            name='eclipse_image_url',
            field=models.TextField(default=''),
        ),
    ]
